.Dd June 25, 2026
.Dt NK2EXPORT 1
.Os
.Sh NAME
.Nm nk2export
.Nd exports items stored in a Nickfile (NK2)
.Sh SYNOPSIS
.Nm nk2export
.Op Fl c Ar codepage
.Op Fl l Ar log_file
.Op Fl t Ar target
.Op Fl hqvV
.Ar source
.Sh DESCRIPTION
.Nm nk2export
is a utility to export items stored in a Nickfile (NK2)
.Pp
.Nm nk2export
is part of the
.Nm libnk2
package.
.Nm libnk2
is a library to access the Nickfile (NK2) format
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar codepage
codepage of ASCII strings, options: ascii, windows-874, windows-932, \
windows-936, windows-949, windows-950, windows-1250, windows-1251, windows-1252 \
(default), windows-1253, windows-1254, windows-1255, windows-1256, windows-1257 \
or windows-1258
.It Fl h
shows this help
.It Fl l Ar log_file
specify the file in which to log information about the exported items
.It Fl q
quiet shows minimal status information
.It Fl t Ar target
specify the target directory to export to (default is the source filename \
followed by .export)
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# nk2export Outlook.NK2
nk2export 20260625
.sp
Opening file.
Exporting aliases.
Exporting alias 1 out of 1.
Export completed.
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \
\-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh SEE ALSO
.Xr nk2info 1
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libnk2/issues
.Sh COPYRIGHT
Copyright (C) 2009-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
