.Dd June 25, 2026
.Dt NK2INFO 1
.Os
.Sh NAME
.Nm nk2info
.Nd determines information about a Nickfile (NK2)
.Sh SYNOPSIS
.Nm nk2info
.Op Fl hvV
.Ar source
.Sh DESCRIPTION
.Nm nk2info
is a utility to determine information about a Nickfile (NK2)
.Pp
.Nm nk2info
is part of the
.Nm libnk2
package.
.Nm libnk2
is a library to access the Nickfile (NK2) format
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
shows this help
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# nk2info Outlook.NK2
nk2info 20260625
.sp
Nickfile information:
	Last modification time	: Jul 04, 2011 09:56:01.557000 UTC
	Number of aliases	: 4
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \
\-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh SEE ALSO
.Xr nk2export 1
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libnk2/issues
.Sh COPYRIGHT
Copyright (C) 2009-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
